get "/demo", _controller: 'demo'
get "/forms", _controller: 'forms'
get "/todos/{_index}", _controller: 'todos'
get "/todos", _controller: 'todos'
get "/blog", _controller: 'blog'
get "/db", _controller: 'db'
get "/db_find", _controller: 'db_find'
get "/items", _controller: 'items'
get "/switches", _controller: 'switches'
get "/awesome", {_awesome: {_cool: 'yes'}}
get '/'
